spring:
  application:
    name: gateway
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    back:
      path: /user/**
      serviceId: user

    auth:
      path: /auth/**
      serviceId: auth

server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

gate:
  ignore:
    startWith: /static,/auth/jwt
auth:
  serviceId: auth
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    id: gateway  #不填则默认读取spring.application.name
    secret: 123456